### ISSUE TITLE
Add ability to not use the wildcard as a filter and be able to enter field name manually.

### ISSUE THREAD

**Issue by daledude** [Chisnet/bespin#1]
Very nice project!

Under the Browser...
I have fields that are not_analyzed strings and your filter won't work with them. 

I also have dynamically created field names per document which are not populated in your field list. Maybe do what Kibana does to get the field names or allow manually entering in the field name (maybe with select2 javascript component).

**Comment by Chisnet** [comment]
Thanks,

I've had a look at the not_analyzed filter issue. For me it just appears to be casing that's the problem? i.e. searching for something in the field that's entirely lowercase still works, but any string containing uppercase returns 0 results. Is that what you were seeing?

As for per document dynamic mappings I'll see what I can do to get those appearing in the list. I'll probably use select2 regardless as it'll help make large lists more manageable and solve a couple of other specific cases as well.

**Comment by daledude** [comment]
Casing does appear to be the issue. My field contains uppercase.

**Comment by Chisnet** [comment]
Both these issues should be improved by the latest release. Filtering on not_analyzed fields is unavoidably case sensitive, but should now work with cased strings.
